#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <grp.h>
#include <pwd.h>
#include <time.h>
#include <dirent.h>
#include <fcntl.h>
#include <math.h>
#include <regex.h>
#include <pthread.h>
#include <ctype.h>
#include <stdbool.h>
#include <getopt.h>
#include <dirent.h>
#include <limits.h>
#include <pwd.h>
#include <utmp.h>
#include <ncurses.h>